spring.application.name=dividend-anatomy

massive.base-url=${MASSIVE_BASE_URL:https://api.massive.com}
massive.api-key=${POLYGON_TOKEN:}
twelvedata.base-url=${TWELVEDATA_BASE_URL:https://api.twelvedata.com}
twelvedata.api-key=${TWELVEDATA_TOKEN:}
